[package]

name = "ethics-gradient"
version = "0.1.0"
authors = [
    "ninjapiraatti <tuomas.louekari@planetoidi.com>"
]

[[bin]]
name = "ethics-gradient"

[dependencies]
piston = "0.52.0"
piston2d-graphics = "0.39.0"
pistoncore-glutin_window = "0.67.0"
piston2d-opengl_graphics = "0.76.0"
